import Head from "next/head";
import styles from "@styles/pages/Portfolio.module.scss";
import { PrismaClient, Reference } from "@prisma/client";
import ReferenceDetail from "@components/modules/ReferenceDetail";
import BigText from "@components/modules/BigText";
import GradientText from "@components/atoms/GradientText";
import ReferenceGrid from "@components/modules/ReferenceGrid";
import MobileNavigation from "@components/layout/MobileNavigation";

interface Props {
  reference: Reference;
}

const ProjectDetail = ({ reference }: Props) => {
  return (
    <>
      <Head>
        <title>{reference.name} - daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <ReferenceDetail reference={reference} />
        <BigText>
          {reference.lead
            .split("_")
            .map((item, i) =>
              i % 2 === 0 ? (
                <span key={i}>{item}</span>
              ) : (
                <GradientText key={i} text={item} />
              )
            )}
        </BigText>
        <ReferenceGrid reference={reference} />
      </main>
      <MobileNavigation
        back={{
          href: "/portfolio",
          label: "Back to portfolio",
        }}
      />
    </>
  );
};

type Params = {
  params: {
    slug: String;
  };
};

export async function getStaticProps({ params }: Params) {
  const prisma = new PrismaClient();
  const reference = await prisma.reference.findFirst({
    include: { tags: { include: { tag: true } } },
    where: {
      slug: {
        equals: params.slug.toString(),
      },
    },
  });
  prisma.$disconnect();

  return {
    props: { reference },
  };
}

export async function getStaticPaths() {
  const prisma = new PrismaClient();
  const references = await prisma.reference.findMany({});
  prisma.$disconnect();
  return {
    paths: references.map((reference) => {
      return {
        params: {
          slug: reference.slug,
        },
      };
    }),
    fallback: false,
  };
}

export default ProjectDetail;
