import Head from "next/head";
import styles from "@styles/pages/Portfolio.module.scss";
import { PrismaClient, Reference } from "@prisma/client";
import ImageRotatedTitle from "@components/modules/ImageRotatedTitle";

interface Props {
  reference: Reference;
}

const Reference = ({ reference }: Props) => {
  return (
    <>
      <Head>
        <title>{reference.name} - daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <ImageRotatedTitle
          image={reference.preview_image}
          heading={reference.name}
          subtitle={reference.description}
        />
      </main>
    </>
  );
};

type Params = {
  params: {
    slug: String;
  };
};

export async function getStaticProps({ params }: Params) {
  const prisma = new PrismaClient();
  const reference = await prisma.reference.findFirst({
    include: { categories: { include: { Category: true } } },
    where: {
      slug: {
        equals: params.slug.toString(),
      },
    },
  });

  return {
    props: { reference },
  };
}
export async function getStaticPaths() {
  const prisma = new PrismaClient();
  const references = await prisma.reference.findMany({});
  return {
    paths: references.map((reference) => {
      return {
        params: {
          slug: reference.slug,
        },
      };
    }),
    fallback: false,
  };
}
export default Reference;
