import Head from "next/head";
import styles from "@styles/pages/Portfolio.module.scss";
import Title from "@components/modules/Title";
import ReferenceLarge from "@components/modules/ReferenceLarge";
import ReferenceSmall from "@components/modules/ReferenceSmall";
import { PrismaClient, Reference } from "@prisma/client";

interface Props {
  references: Reference[];
}

const Portfolio = ({ references }: Props) => {
  return (
    <>
      <Head>
        <title>Portfolio - daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Title
          smallHeading="This is"
          largeHeadingWhite="my"
          largeHeadingColor="Portfolio"
        />
        {references && references[0] && (
          <ReferenceLarge reference={references[0]} subtitle="Most recent" />
        )}
        {references.slice(1).map((reference, i) => (
          <ReferenceSmall
            key={reference.id}
            reference={reference}
            textRight={i % 2 == 1}
          />
        ))}
      </main>
    </>
  );
};

export async function getStaticProps() {
  const prisma = new PrismaClient();
  const references = await prisma.reference.findMany({
    include: { categories: { include: { Category: true } } },
    orderBy: {
      create_date: "desc",
    },
  });

  return {
    props: { references },
  };
}

export default Portfolio;
