import Head from "next/head";
import styles from "@styles/pages/Portfolio.module.scss";
import Title from "@components/modules/Title";
import ReferenceLarge from "@components/modules/ReferenceLarge";
import ReferenceSmall from "@components/modules/ReferenceSmall";
import { PrismaClient, Reference, ReferenceTag, Tag } from "@prisma/client";

export type TaggedReference = Reference & {
  tags: (ReferenceTag & { tag: Tag | null })[];
};
interface Props {
  references: TaggedReference[];
}

const Portfolio = ({ references }: Props) => {
  return (
    <>
      <Head>
        <title>Portfolio - daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Title smallHeading="my" largeHeadingColor="Portfolio" />
        {references && references[0] && (
          <ReferenceLarge reference={references[0]} />
        )}
        <div className="container">
          <div className={styles["reference-list"]}>
            <div className={styles["reference-column"]}>
              {references &&
                references
                  .slice(1)
                  .map(
                    (reference, i) =>
                      i % 2 === 0 && (
                        <ReferenceSmall
                          key={reference.id}
                          reference={reference}
                        />
                      )
                  )}
            </div>
            <div className={styles["reference-column"]}>
              {references &&
                references
                  .slice(1)
                  .map(
                    (reference, i) =>
                      i % 2 !== 0 && (
                        <ReferenceSmall
                          key={reference.id}
                          reference={reference}
                        />
                      )
                  )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export async function getStaticProps() {
  const prisma = new PrismaClient();
  const references = await prisma.reference.findMany({
    include: { tags: { include: { tag: true } } },
  });
  prisma.$disconnect();

  return {
    props: { references },
  };
}

export default Portfolio;
