import type { NextPage } from "next";
import Head from "next/head";
import styles from "@styles/pages/Portfolio.module.scss";
import Title from "@components/modules/Title";
import ReferenceLarge from "@components/modules/ReferenceLarge";
import ReferenceSmall from "@components/modules/ReferenceSmall";

const Portfolio: NextPage = () => {
  return (
    <>
      <Head>
        <title>Portfolio - daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Title
          smallHeading="This is"
          largeHeadingWhite="my"
          largeHeadingColor="Portfolio"
        />
        <ReferenceLarge
          reference={{
            id: "x",
            name: "wastend",
            description: "some project",
            slug: "wastend",
            create_date: new Date(),
            preview_image: "/image.jpg",
          }}
          subtitle="Most recent"
        />
        <ReferenceSmall
          reference={{
            id: "x",
            name: "wastend",
            description: "some project",
            slug: "wastend",
            create_date: new Date(),
            preview_image: "/image.jpg",
          }}
        />
        <ReferenceSmall
          textRight
          reference={{
            id: "x",
            name: "wastend",
            description: "some project",
            slug: "wastend",
            create_date: new Date(),
            preview_image: "/image.jpg",
          }}
        />
      </main>
    </>
  );
};

export default Portfolio;
