import Head from "next/head";
import styles from "@styles/pages/Portfolio.module.scss";
import { Post, PrismaClient } from "@prisma/client";

interface Props {
  post: Post;
}

const Post = ({ post }: Props) => {
  return (
    <>
      <Head>
        <title>{post.name} - daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
};

type Params = {
  params: {
    slug: String;
  };
};

export async function getStaticProps({ params }: Params) {
  const prisma = new PrismaClient();
  const reference = await prisma.post.findFirst({
    where: {
      slug: {
        equals: params.slug.toString(),
      },
    },
  });

  return {
    props: { reference },
  };
}
export async function getStaticPaths() {
  const prisma = new PrismaClient();
  const posts = await prisma.post.findMany({});
  return {
    paths: posts.map((post) => {
      return {
        params: {
          slug: post.slug,
        },
      };
    }),
    fallback: false,
  };
}
export default Post;
