import Head from "next/head";
import styles from "@styles/pages/Blog.module.scss";
import Title from "@components/modules/Title";
import { Post, PostTag, PrismaClient, Tag } from "@prisma/client";
import BlogPostPreview from "@components/modules/BlogPostPreview";

export type TaggedPost = Post & {
  tags: (PostTag & { tag: Tag | null })[];
};

interface Props {
  posts: TaggedPost[];
}

const Blog = ({ posts }: Props) => {
  return (
    <>
      <Head>
        <title>Portfolio - daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Title smallHeading="MY" largeHeadingColor="Blog" />
        <div className="margin-large-top container">
          <div className={styles["blog-grid"]}>
            {posts && posts[0] && (
              <div className={styles["blog-item-large"]}>
                <BlogPostPreview post={posts[0]} large />
              </div>
            )}
            {posts.slice(1).map((post) => (
              <div className={styles["blog-item"]} key={post.id}>
                <BlogPostPreview post={post} />
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export async function getStaticProps() {
  const prisma = new PrismaClient();
  const posts = await prisma.post.findMany({
    orderBy: {
      createDate: "desc",
    },
    include: { tags: { include: { tag: true } } },
  });
  prisma.$disconnect();

  return {
    props: { posts },
  };
}

export default Blog;
