import Title from "@components/modules/Title";
import Head from "next/head";

const page404 = () => {
  return (
    <>
      <Head>
        <title>404 not found - daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Title smallHeading="404" largeHeadingColor="page not found" />
      </main>
    </>
  );
};

export default page404;
