import type { NextPage } from "next";
import Head from "next/head";
import styles from "@styles/pages/Home.module.scss";
import Introduction from "@components/modules/Introduction";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>daniel plan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Introduction />
      </main>
    </>
  );
};

export default Home;
